### ISSUE TITLE
Honcho kills backing services before celery workers

### ISSUE THREAD

**Issue by davidlmorton** [genome/ptero#17]
This causes us to see a long stacktrace about connection errors at the end of the logs created during testing.  We know that we can ignore such things, but it is an annoyance and potentially distressing to new developers.

**Comment by davidlmorton** [comment]
We want to make sure the celery workers are brought down BEFORE the redis/rabbitmq processes on which they depend.

**Comment by mkiwala** [comment]
A typical stack trace:

```
11:39:59 fork_worker.1 | worker: Warm shutdown (MainProcess)
11:39:59 fork_worker.1 | Traceback (most recent call last):
11:39:59 fork_worker.1 |   File "/Users/mkiwala/Projects/ptero/services/shell-command/.tox/py27/lib/python2.7/site-packages/eventlet/hubs/kqueue.py", line 107, in wait
11:39:59 fork_worker.1 |     readers.get(fileno, noop).cb(fileno)
11:39:59 fork_worker.1 |   File "/Users/mkiwala/Projects/ptero/services/shell-command/.tox/py27/lib/python2.7/site-packages/celery/worker/pidbox.py", line 112, in loop
11:39:59 fork_worker.1 |     connection.drain_events(timeout=1.0)
11:39:59 fork_worker.1 |   File "/Users/mkiwala/Projects/ptero/services/shell-command/.tox/py27/lib/python2.7/site-packages/kombu/connection.py", line 275, in drain_events
11:39:59 fork_worker.1 |     return self.transport.drain_events(self.connection, **kwargs)
11:39:59 fork_worker.1 |   File "/Users/mkiwala/Projects/ptero/services/shell-command/.tox/py27/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 91, in drain_events
11:39:59 fork_worker.1 |     return connection.drain_events(**kwargs)
11:39:59 fork_worker.1 |   File "/Users/mkiwala/Projects/ptero/services/shell-command/.tox/py27/lib/python2.7/site-packages/amqp/connection.py", line 302, in drain_events
11:39:59 fork_worker.1 |     chanmap, None, timeout=timeout,
11:39:59 fork_worker.1 |   File "/Users/mkiwala/Projects/ptero/services/shell-command/.tox/py27/lib/python2.7/site-packages/amqp/connection.py", line 365, in _wait_multiple
11:39:59 fork_worker.1 |     channel, method_sig, args, content = read_timeout(timeout)
11:39:59 fork_worker.1 |   File "/Users/mkiwala/Projects/ptero/services/shell-command/.tox/py27/lib/python2.7/site-packages/amqp/connection.py", line 336, in read_timeout
11:39:59 fork_worker.1 |     return self.method_reader.read_method()
11:39:59 fork_worker.1 |   File "/Users/mkiwala/Projects/ptero/services/shell-command/.tox/py27/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
11:39:59 fork_worker.1 |     raise m
11:39:59 fork_worker.1 | IOError: Socket closed
11:39:59 fork_worker.1 | Removing descriptor: 7L
11:39:59 fork_worker.1 | process terminated
```
